server:
  port: 9000
  tomcat:
    uri-encoding: utf-8
  context-path: /boom
spring:
  datasource:
      name: boomsystem
      url: jdbc:mysql://localhost:3306/boomsystem
      username: root
      password: summer
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    database: 0
    hotst: localhost
    password: summer
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0
    sentinel:
      master: #main node name
      nodes:  #all nodes' name separated by comma,host:port
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

mybatis:
  type-aliases-package: com.boom.rbac.domain
  mapper-locations: classpath:mapper/**/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

